# Generated by Django 3.0.6 on 2020-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
