# Generated by Django 3.0.6 on 2020-07-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sller',
            new_name='seller',
        ),
    ]
