# Generated by Django 3.0.6 on 2020-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200703_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourlyRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
