# Generated by Django 3.0.6 on 2020-07-19 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200719_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_buyer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_seller',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 5, 42, 6, 270729)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 5, 42, 6, 266047, tzinfo=utc)),
        ),
    ]
