# Generated by Django 3.0.6 on 2020-07-21 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200721_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Resumate',
            new_name='resumate',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 3, 49, 17, 573406)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 3, 49, 17, 569749, tzinfo=utc)),
        ),
    ]
