# Generated by Django 3.0.6 on 2020-07-21 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200721_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='open_foroffer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 43, 13, 701038)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 43, 13, 697329, tzinfo=utc)),
        ),
    ]
