# Generated by Django 3.0.6 on 2020-07-21 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200721_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 52, 1, 677011)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 52, 1, 679144)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 52, 1, 675186, tzinfo=utc)),
        ),
    ]
