# Generated by Django 3.0.6 on 2020-08-06 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200728_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 6, 42, 42, 360041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 8, 42, 42, 365074)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 6, 42, 42, 352115, tzinfo=utc)),
        ),
    ]
