# Generated by Django 3.0.6 on 2020-08-06 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200806_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 17, 11, 56, 980179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 23, 11, 56, 983177)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 17, 11, 56, 978180, tzinfo=utc)),
        ),
    ]
