# Generated by Django 3.0.6 on 2020-08-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='password',
            new_name='password1',
        ),
    ]
