# Generated by Django 3.0.6 on 2020-08-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('mess', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
