# Generated by Django 3.0.6 on 2020-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200805_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('mess', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='ddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='messageinfo',
            name='food',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
