# Generated by Django 3.0.6 on 2020-08-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200805_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzinfo',
            name='mess',
        ),
    ]
