# Generated by Django 3.0.6 on 2020-08-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_quizzinfo_mess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizzinfo',
            new_name='Quizz',
        ),
        migrations.RenameField(
            model_name='quizz',
            old_name='ddate',
            new_name='date',
        ),
    ]
