# Generated by Django 3.0.6 on 2020-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200805_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
