# Generated by Django 3.0.6 on 2020-08-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200805_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='file',
            new_name='filee',
        ),
    ]
