# Generated by Django 3.0.6 on 2020-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200805_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='filee',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
