# Generated by Django 3.0.6 on 2020-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20200805_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
