# Generated by Django 3.0.6 on 2020-08-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200806_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='password2',
        ),
    ]
